"""baseline schema"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '070714be7e3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clarification_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('original_input', sa.Text(), nullable=False),
    sa.Column('uncertainty_type', sa.String(length=64), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('context_provided', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('selected_option', sa.String(length=128), nullable=True),
    sa.Column('resolved_action', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timeout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audit_log_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('code_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('current_file', sa.String(length=512), nullable=True),
    sa.Column('current_language', sa.String(length=32), nullable=True),
    sa.Column('cursor_position', sa.JSON(), nullable=True),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(length=128), nullable=True),
    sa.Column('open_files', sa.JSON(), nullable=True),
    sa.Column('recent_edits', sa.JSON(), nullable=True),
    sa.Column('active_patterns', sa.JSON(), nullable=True),
    sa.Column('project_root', sa.String(length=512), nullable=True),
    sa.Column('project_type', sa.String(length=64), nullable=True),
    sa.Column('framework', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('project', sa.String(length=128), nullable=True),
    sa.Column('module', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('lines_of_code', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('return_type', sa.String(length=128), nullable=True),
    sa.Column('times_recalled', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('last_validated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=256), nullable=False),
    sa.Column('symbol_type', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('project', sa.String(length=128), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_symbols_symbol'), 'code_symbols', ['symbol'], unique=False)
    op.create_table('committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=True),
    sa.Column('member_ids', sa.JSON(), nullable=True),
    sa.Column('min_members', sa.Integer(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('default_quorum', sa.Integer(), nullable=True),
    sa.Column('default_threshold', sa.Float(), nullable=True),
    sa.Column('auto_assign_categories', sa.JSON(), nullable=True),
    sa.Column('auto_assign_risk_levels', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('committee_name')
    )
    op.create_table('constitutional_compliance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=256), nullable=True),
    sa.Column('principles_checked', sa.JSON(), nullable=True),
    sa.Column('principles_passed', sa.JSON(), nullable=True),
    sa.Column('principles_failed', sa.JSON(), nullable=True),
    sa.Column('compliant', sa.Boolean(), nullable=False),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('explanation_provided', sa.Boolean(), nullable=True),
    sa.Column('reasoning_logged', sa.Boolean(), nullable=True),
    sa.Column('approval_obtained', sa.Boolean(), nullable=True),
    sa.Column('verification_signed', sa.Boolean(), nullable=True),
    sa.Column('violation_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('audit_log_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constitutional_principles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principle_name', sa.String(length=128), nullable=False),
    sa.Column('principle_level', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('enforcement_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('governance_policy_ids', sa.JSON(), nullable=True),
    sa.Column('hunter_rule_ids', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('applies_to', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('immutable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principle_name')
    )
    op.create_table('duration_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('avg_duration', sa.Float(), nullable=False),
    sa.Column('std_deviation', sa.Float(), nullable=True),
    sa.Column('min_duration', sa.Float(), nullable=True),
    sa.Column('max_duration', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('confidence_interval_lower', sa.Float(), nullable=True),
    sa.Column('confidence_interval_upper', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_type')
    )
    op.create_table('event_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.JSON(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('avg_duration', sa.Float(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('goal_text', sa.Text(), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('governance_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=64), nullable=False),
    sa.Column('member_type', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('committees', sa.JSON(), nullable=True),
    sa.Column('vote_weight', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('suspended', sa.Boolean(), nullable=True),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('public_key', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_vote_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=True),
    sa.Column('votes_approved', sa.Integer(), nullable=True),
    sa.Column('votes_rejected', sa.Integer(), nullable=True),
    sa.Column('votes_abstained', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_table('governance_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('policy_name', sa.String(length=128), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('action_payload', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('resource', sa.String(length=256), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('committee', sa.String(length=64), nullable=True),
    sa.Column('quorum_required', sa.Integer(), nullable=True),
    sa.Column('approval_threshold', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('votes_approve', sa.Integer(), nullable=True),
    sa.Column('votes_reject', sa.Integer(), nullable=True),
    sa.Column('votes_abstain', sa.Integer(), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=True),
    sa.Column('weighted_approve', sa.Float(), nullable=True),
    sa.Column('weighted_reject', sa.Float(), nullable=True),
    sa.Column('weighted_abstain', sa.Float(), nullable=True),
    sa.Column('total_weighted', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('hunter_alerts', sa.JSON(), nullable=True),
    sa.Column('verification_envelope_id', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('voting_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audit_log_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('grace_architecture_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_type', sa.String(length=64), nullable=False),
    sa.Column('component', sa.String(length=128), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=True),
    sa.Column('pattern_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('code_example', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('usage_guide', sa.Text(), nullable=True),
    sa.Column('integration_points', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grace_extension_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('feature_request', sa.Text(), nullable=False),
    sa.Column('business_need', sa.Text(), nullable=True),
    sa.Column('affected_components', sa.JSON(), nullable=True),
    sa.Column('new_components_needed', sa.JSON(), nullable=True),
    sa.Column('integration_points', sa.JSON(), nullable=True),
    sa.Column('implementation_plan', sa.JSON(), nullable=True),
    sa.Column('estimated_effort_hours', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('code_generated', sa.Text(), nullable=True),
    sa.Column('tests_generated', sa.Text(), nullable=True),
    sa.Column('governance_approved', sa.Boolean(), nullable=True),
    sa.Column('parliament_session_id', sa.String(length=128), nullable=True),
    sa.Column('constitutional_compliant', sa.Boolean(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('deployed', sa.Boolean(), nullable=True),
    sa.Column('revenue_impact', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('immutable_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=256), nullable=True),
    sa.Column('subsystem', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_hash'),
    sa.UniqueConstraint('sequence')
    )
    op.create_table('issue_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('likely_cause', sa.Text(), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('action_label', sa.String(length=256), nullable=True),
    sa.Column('action_payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('applied_fix', sa.Text(), nullable=True),
    sa.Column('fix_result', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('artifact_metadata', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('ingested_by', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('marketplace_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('budget_type', sa.String(length=32), nullable=True),
    sa.Column('client_id', sa.String(length=128), nullable=True),
    sa.Column('client_name', sa.String(length=128), nullable=True),
    sa.Column('client_rating', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('hunter_score', sa.Float(), nullable=True),
    sa.Column('grace_recommendation', sa.Text(), nullable=True),
    sa.Column('skills_required', sa.JSON(), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('memory_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('artifact_metadata', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('memory_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('artifact_path', sa.String(length=512), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('previous_content_hash', sa.String(length=64), nullable=True),
    sa.Column('new_content_hash', sa.String(length=64), nullable=False),
    sa.Column('operation_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_operation_hash', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('operation_metadata', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=True),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_loop_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=128), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('config_type', sa.String(length=32), nullable=True),
    sa.Column('last_updated_by', sa.String(length=64), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('meta_meta_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_analysis_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=128), nullable=True),
    sa.Column('before_value', sa.Float(), nullable=True),
    sa.Column('after_value', sa.Float(), nullable=True),
    sa.Column('improvement', sa.Float(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('deployment_status', sa.String(length=32), nullable=True),
    sa.Column('event_metadata', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('model_type', sa.String(length=64), nullable=True),
    sa.Column('model_hash', sa.String(length=64), nullable=False),
    sa.Column('dataset_hash', sa.String(length=64), nullable=True),
    sa.Column('trust_score_min', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('training_data_count', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=True),
    sa.Column('deployment_status', sa.String(length=32), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('signature', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parliament_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=64), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=128), nullable=False),
    sa.Column('stripe_payment_method_id', sa.String(length=128), nullable=False),
    sa.Column('payment_type', sa.String(length=32), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('brand', sa.String(length=32), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_type', sa.String(length=64), nullable=False),
    sa.Column('predicted_event', sa.String(length=128), nullable=True),
    sa.Column('predicted_probability', sa.Float(), nullable=True),
    sa.Column('actual_event', sa.String(length=128), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sandbox_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sandbox_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secret_access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret_key', sa.String(length=128), nullable=False),
    sa.Column('accessor', sa.String(length=64), nullable=False),
    sa.Column('access_type', sa.String(length=32), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('denied_reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('service', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret_key', sa.String(length=128), nullable=False),
    sa.Column('secret_type', sa.String(length=64), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('encryption_method', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('service', sa.String(length=128), nullable=True),
    sa.Column('allowed_users', sa.JSON(), nullable=True),
    sa.Column('allowed_services', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotation_days', sa.Integer(), nullable=True),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accessed_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_by', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('verification_envelope_id', sa.Integer(), nullable=True),
    sa.Column('audit_log_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_key')
    )
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('predicted_outcome', sa.JSON(), nullable=False),
    sa.Column('actual_outcome', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stripe_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(length=128), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=128), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=128), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('refunded', sa.Boolean(), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('refund_approved_by', sa.String(length=64), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('governance_approval_id', sa.Integer(), nullable=True),
    sa.Column('parliament_approval_id', sa.Integer(), nullable=True),
    sa.Column('verification_signature', sa.String(length=256), nullable=True),
    sa.Column('transaction_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_invoice_id')
    )
    op.create_table('stripe_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processing_result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_event_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temporal_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=True),
    sa.Column('expected_duration', sa.Float(), nullable=True),
    sa.Column('actual_duration', sa.Float(), nullable=True),
    sa.Column('deviation_sigma', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('dataset_trust_threshold', sa.Float(), nullable=True),
    sa.Column('samples_used', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('final_loss', sa.Float(), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('signature', sa.String(length=256), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcendence_collaborative_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.String(length=128), nullable=False),
    sa.Column('proposal_type', sa.String(length=64), nullable=False),
    sa.Column('grace_proposal', sa.Text(), nullable=False),
    sa.Column('grace_reasoning', sa.Text(), nullable=False),
    sa.Column('grace_confidence', sa.Float(), nullable=False),
    sa.Column('business_context', sa.Text(), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('risk_assessment', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('your_response', sa.Text(), nullable=True),
    sa.Column('your_modifications', sa.JSON(), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=True),
    sa.Column('execution_result', sa.JSON(), nullable=True),
    sa.Column('outcome_success', sa.Boolean(), nullable=True),
    sa.Column('grace_learned', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_table('transcendence_learning_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.String(length=128), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('stage_ingest', sa.JSON(), nullable=True),
    sa.Column('stage_understand', sa.JSON(), nullable=True),
    sa.Column('stage_interpret', sa.JSON(), nullable=True),
    sa.Column('stage_intent', sa.JSON(), nullable=True),
    sa.Column('stage_apply', sa.JSON(), nullable=True),
    sa.Column('stage_create', sa.JSON(), nullable=True),
    sa.Column('stage_manage', sa.JSON(), nullable=True),
    sa.Column('stage_adapt', sa.JSON(), nullable=True),
    sa.Column('verifications', sa.JSON(), nullable=True),
    sa.Column('governance_approved', sa.Boolean(), nullable=True),
    sa.Column('parliament_session_id', sa.String(length=128), nullable=True),
    sa.Column('constitutional_compliant', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('value_created', sa.Text(), nullable=True),
    sa.Column('revenue_impact', sa.Float(), nullable=True),
    sa.Column('memory_refs', sa.JSON(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id')
    )
    op.create_table('transcendence_trusted_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.String(length=32), nullable=True),
    sa.Column('whitelist_status', sa.String(length=32), nullable=True),
    sa.Column('alignment_standards', sa.JSON(), nullable=True),
    sa.Column('quality_criteria', sa.JSON(), nullable=True),
    sa.Column('auto_ingest', sa.Boolean(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=True),
    sa.Column('use_for_training', sa.Boolean(), nullable=True),
    sa.Column('training_weight', sa.Float(), nullable=True),
    sa.Column('added_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('ingestion_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trusted_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=256), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(length=64), nullable=True),
    sa.Column('auto_approve_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('password_hash_is_legacy', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('verification_envelopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=256), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('signature', sa.String(length=256), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('criteria_met', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id')
    )
    op.create_table('verification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verification_type', sa.String(length=64), nullable=False),
    sa.Column('target_component', sa.String(length=128), nullable=True),
    sa.Column('verification_method', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('causal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('trigger_message_id', sa.Integer(), nullable=True),
    sa.Column('response_message_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['response_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['trigger_message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constitutional_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principle_id', sa.Integer(), nullable=False),
    sa.Column('violation_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=256), nullable=True),
    sa.Column('detected_by', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('remediation_action', sa.Text(), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['principle_id'], ['constitutional_principles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('governance_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(length=16), nullable=False),
    sa.Column('vote_weight', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('automated', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('vote_signature', sa.String(length=256), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('audit_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['governance_members.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['governance_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_deliverables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_job_id', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_paths', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_feedback', sa.Text(), nullable=True),
    sa.Column('revision_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['marketplace_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('marketplace_job_id', sa.String(length=128), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('auto_generated', sa.Boolean(), nullable=True),
    sa.Column('grace_approved', sa.Boolean(), nullable=True),
    sa.Column('human_reviewed', sa.Boolean(), nullable=True),
    sa.Column('thread_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['marketplace_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_job_id', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('proposal_text', sa.Text(), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('governance_approved', sa.Boolean(), nullable=True),
    sa.Column('parliament_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_response', sa.Text(), nullable=True),
    sa.Column('acceptance_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['marketplace_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operational_tenets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenet_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rule_example', sa.Text(), nullable=True),
    sa.Column('principle_id', sa.Integer(), nullable=True),
    sa.Column('integration_point', sa.String(length=64), nullable=False),
    sa.Column('enforcement_method', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['principle_id'], ['constitutional_principles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenet_name')
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decision_by', sa.String(length=64), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=True),
    sa.Column('resource', sa.String(length=128), nullable=True),
    sa.Column('policy_checked', sa.String(length=128), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('governance_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('healing_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=True),
    sa.Column('resource', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cognition_gc_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_name', sa.String(length=64), nullable=False),
    sa.Column('artifacts_scanned', sa.Integer(), nullable=True),
    sa.Column('artifacts_archived', sa.Integer(), nullable=True),
    sa.Column('artifacts_deleted', sa.Integer(), nullable=True),
    sa.Column('threshold_trust', sa.Float(), nullable=True),
    sa.Column('threshold_age_hours', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cognition_memory_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_ref', sa.String(length=128), nullable=False),
    sa.Column('loop_id', sa.String(length=128), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('output_type', sa.String(length=32), nullable=False),
    sa.Column('result_data', sa.Text(), nullable=False),
    sa.Column('reasoning_chain_id', sa.String(length=128), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('provenance_score', sa.Float(), nullable=True),
    sa.Column('consensus_score', sa.Float(), nullable=True),
    sa.Column('governance_score', sa.Float(), nullable=True),
    sa.Column('usage_score', sa.Float(), nullable=True),
    sa.Column('decay_curve', sa.String(length=32), nullable=True),
    sa.Column('half_life_hours', sa.Float(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('constitutional_compliance', sa.Boolean(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('policy_tags', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('verification_envelope_id', sa.String(length=128), nullable=True),
    sa.Column('audit_log_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_ref')
    )
    op.create_table('cognition_memory_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('index_type', sa.String(length=32), nullable=False),
    sa.Column('index_value', sa.String(length=256), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['cognition_memory_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cognition_trust_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('old_trust_score', sa.Float(), nullable=False),
    sa.Column('new_trust_score', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('provenance_delta', sa.Float(), nullable=True),
    sa.Column('consensus_delta', sa.Float(), nullable=True),
    sa.Column('governance_delta', sa.Float(), nullable=True),
    sa.Column('usage_delta', sa.Float(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['cognition_memory_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('sustained', sa.Boolean(), nullable=True),
    sa.Column('window_days', sa.Integer(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('benchmark_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_history_id'), 'benchmark_history', ['id'], unique=False)
    op.create_index(op.f('ix_benchmark_history_metric_name'), 'benchmark_history', ['metric_name'], unique=False)
    op.create_index(op.f('ix_benchmark_history_timestamp'), 'benchmark_history', ['timestamp'], unique=False)
    op.create_table('domain_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('health', sa.Float(), nullable=True),
    sa.Column('trust', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('kpis', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('health_trend', sa.String(length=20), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('has_alerts', sa.Boolean(), nullable=True),
    sa.Column('alert_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_metrics_domain'), 'domain_metrics', ['domain'], unique=True)
    op.create_index(op.f('ix_domain_metrics_id'), 'domain_metrics', ['id'], unique=False)
    op.create_table('metric_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('kpi', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metric_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_domain_kpi_timestamp', 'metric_events', ['domain', 'kpi', 'timestamp'], unique=False)
    op.create_index(op.f('ix_metric_events_domain'), 'metric_events', ['domain'], unique=False)
    op.create_index(op.f('ix_metric_events_id'), 'metric_events', ['id'], unique=False)
    op.create_index(op.f('ix_metric_events_kpi'), 'metric_events', ['kpi'], unique=False)
    op.create_index(op.f('ix_metric_events_timestamp'), 'metric_events', ['timestamp'], unique=False)
    op.create_table('metrics_rollups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('kpi', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('avg_value', sa.Float(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('sum_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_domain_kpi_period', 'metrics_rollups', ['domain', 'kpi', 'period', 'period_start'], unique=False)
    op.create_index(op.f('ix_metrics_rollups_domain'), 'metrics_rollups', ['domain'], unique=False)
    op.create_index(op.f('ix_metrics_rollups_id'), 'metrics_rollups', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_rollups_kpi'), 'metrics_rollups', ['kpi'], unique=False)
    op.create_index(op.f('ix_metrics_rollups_period_start'), 'metrics_rollups', ['period_start'], unique=False)
    op.create_table('saas_readiness_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('overall_health', sa.Float(), nullable=False),
    sa.Column('overall_trust', sa.Float(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('saas_ready', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saas_readiness_events_id'), 'saas_readiness_events', ['id'], unique=False)
    op.create_index(op.f('ix_saas_readiness_events_triggered_at'), 'saas_readiness_events', ['triggered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saas_readiness_events_triggered_at'), table_name='saas_readiness_events')
    op.drop_index(op.f('ix_saas_readiness_events_id'), table_name='saas_readiness_events')
    op.drop_table('saas_readiness_events')
    op.drop_index(op.f('ix_metrics_rollups_period_start'), table_name='metrics_rollups')
    op.drop_index(op.f('ix_metrics_rollups_kpi'), table_name='metrics_rollups')
    op.drop_index(op.f('ix_metrics_rollups_id'), table_name='metrics_rollups')
    op.drop_index(op.f('ix_metrics_rollups_domain'), table_name='metrics_rollups')
    op.drop_index('idx_domain_kpi_period', table_name='metrics_rollups')
    op.drop_table('metrics_rollups')
    op.drop_index(op.f('ix_metric_events_timestamp'), table_name='metric_events')
    op.drop_index(op.f('ix_metric_events_kpi'), table_name='metric_events')
    op.drop_index(op.f('ix_metric_events_id'), table_name='metric_events')
    op.drop_index(op.f('ix_metric_events_domain'), table_name='metric_events')
    op.drop_index('idx_domain_kpi_timestamp', table_name='metric_events')
    op.drop_table('metric_events')
    op.drop_index(op.f('ix_domain_metrics_id'), table_name='domain_metrics')
    op.drop_index(op.f('ix_domain_metrics_domain'), table_name='domain_metrics')
    op.drop_table('domain_metrics')
    op.drop_index(op.f('ix_benchmark_history_timestamp'), table_name='benchmark_history')
    op.drop_index(op.f('ix_benchmark_history_metric_name'), table_name='benchmark_history')
    op.drop_index(op.f('ix_benchmark_history_id'), table_name='benchmark_history')
    op.drop_table('benchmark_history')
    op.drop_table('cognition_trust_events')
    op.drop_table('cognition_memory_index')
    op.drop_table('cognition_memory_artifacts')
    op.drop_table('cognition_gc_log')
    op.drop_table('security_rules')
    op.drop_table('security_events')
    op.drop_table('health_checks')
    op.drop_table('healing_actions')
    op.drop_table('governance_policies')
    op.drop_table('audit_log')
    op.drop_table('approval_requests')
    op.drop_table('operational_tenets')
    op.drop_table('marketplace_proposals')
    op.drop_table('marketplace_messages')
    op.drop_table('marketplace_deliverables')
    op.drop_table('governance_votes')
    op.drop_table('constitutional_violations')
    op.drop_table('causal_events')
    op.drop_table('verification_events')
    op.drop_table('verification_envelopes')
    op.drop_table('users')
    op.drop_table('trusted_sources')
    op.drop_table('transcendence_trusted_sources')
    op.drop_table('transcendence_learning_cycles')
    op.drop_table('transcendence_collaborative_decisions')
    op.drop_table('training_runs')
    op.drop_table('temporal_anomalies')
    op.drop_table('tasks')
    op.drop_table('stripe_webhooks')
    op.drop_table('stripe_transactions')
    op.drop_table('simulations')
    op.drop_table('secrets')
    op.drop_table('secret_access_log')
    op.drop_table('sandbox_runs')
    op.drop_table('sandbox_files')
    op.drop_table('prediction_records')
    op.drop_table('payment_methods')
    op.drop_table('parliament_config')
    op.drop_table('ml_models')
    op.drop_table('ml_events')
    op.drop_table('meta_meta_evaluations')
    op.drop_table('meta_loop_configs')
    op.drop_table('meta_analyses')
    op.drop_table('memory_operations')
    op.drop_table('memory_events')
    op.drop_table('memory_artifacts')
    op.drop_table('marketplace_jobs')
    op.drop_table('knowledge_artifacts')
    op.drop_table('issue_reports')
    op.drop_table('immutable_log')
    op.drop_table('grace_extension_requests')
    op.drop_table('grace_architecture_knowledge')
    op.drop_table('governance_sessions')
    op.drop_table('governance_members')
    op.drop_table('goals')
    op.drop_table('execution_tasks')
    op.drop_table('event_patterns')
    op.drop_table('duration_estimates')
    op.drop_table('constitutional_principles')
    op.drop_table('constitutional_compliance')
    op.drop_table('committees')
    op.drop_index(op.f('ix_code_symbols_symbol'), table_name='code_symbols')
    op.drop_table('code_symbols')
    op.drop_table('code_patterns')
    op.drop_table('code_contexts')
    op.drop_table('clarification_requests')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
