"""
Worker Configuration - Uvicorn/Gunicorn worker settings
"""

import os
import multiprocessing
from dataclasses import dataclass
from typing import Optional


@dataclass
class WorkerConfig:
    """Configuration for application workers"""
    workers: int
    worker_class: str = "uvicorn.workers.UvicornWorker"
    worker_connections: int = 1000
    max_requests: int = 10000
    max_requests_jitter: int = 1000
    timeout: int = 300
    keepalive: int = 5
    
    bind: str = "0.0.0.0:8000"
    backlog: int = 2048
    
    accesslog: str = "-"
    errorlog: str = "-"
    loglevel: str = "info"
    
    proc_name: str = "grace"
    
    daemon: bool = False
    pidfile: Optional[str] = None
    umask: int = 0
    user: Optional[int] = None
    group: Optional[int] = None
    tmp_upload_dir: Optional[str] = None
    
    keyfile: Optional[str] = None
    certfile: Optional[str] = None
    
    def to_gunicorn_config(self) -> dict:
        """Convert to Gunicorn configuration dict"""
        return {
            "workers": self.workers,
            "worker_class": self.worker_class,
            "worker_connections": self.worker_connections,
            "max_requests": self.max_requests,
            "max_requests_jitter": self.max_requests_jitter,
            "timeout": self.timeout,
            "keepalive": self.keepalive,
            "bind": self.bind,
            "backlog": self.backlog,
            "accesslog": self.accesslog,
            "errorlog": self.errorlog,
            "loglevel": self.loglevel,
            "proc_name": self.proc_name,
            "daemon": self.daemon,
            "pidfile": self.pidfile,
            "umask": self.umask,
            "user": self.user,
            "group": self.group,
            "tmp_upload_dir": self.tmp_upload_dir,
            "keyfile": self.keyfile,
            "certfile": self.certfile,
        }


def get_worker_config(
    environment: str = "production",
    custom_workers: Optional[int] = None
) -> WorkerConfig:
    """
    Get worker configuration based on environment.
    
    Args:
        environment: "development", "staging", or "production"
        custom_workers: Override worker count
    
    Returns:
        WorkerConfig instance
    """
    cpu_count = multiprocessing.cpu_count()
    
    if custom_workers:
        workers = custom_workers
    elif environment == "development":
        workers = 1
    elif environment == "staging":
        workers = max(2, cpu_count // 2)
    else:  # production
        workers = (cpu_count * 2) + 1  # Gunicorn recommendation
    
    bind = os.getenv("GRACE_BIND", "0.0.0.0:8000")
    loglevel = os.getenv("GRACE_LOG_LEVEL", "info")
    
    return WorkerConfig(
        workers=workers,
        bind=bind,
        loglevel=loglevel,
        worker_connections=1000 if environment == "development" else 2000,
        max_requests=1000 if environment == "development" else 10000,
        timeout=120 if environment == "development" else 300
    )


def create_gunicorn_config_file(
    config: WorkerConfig,
    output_path: str = "gunicorn.conf.py"
):
    """Create a Gunicorn configuration file"""
    config_dict = config.to_gunicorn_config()
    
    lines = [
        "# Gunicorn configuration file",
        "# Generated by Grace scaling configuration",
        "",
    ]
    
    for key, value in config_dict.items():
        if value is not None:
            if isinstance(value, str):
                lines.append(f'{key} = "{value}"')
            else:
                lines.append(f'{key} = {value}')
    
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))
